# Generated by Django 5.2.1 on 2025-06-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_policy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
