# Generated by Django 5.2.6 on 2025-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companycertificate_companymilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='logo',
            field=models.ImageField(default=0, upload_to='MTFabout/'),
            preserve_default=False,
        ),
    ]
