# Generated by Django 5.2.6 on 2025-10-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutcompany_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='logo',
        ),
    ]
