# Generated by Django 5.2.1 on 2025-06-10 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pickuppoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='completion_date',
            new_name='sale_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=100, help_text='Минимальное количество для оптового заказа', validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('sold', 'Продан')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Минимальный заказ - 100 штук', validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
