# Generated by Django 5.2.1 on 2025-06-23 15:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_order_options_and_more'),
        ('users', '0004_remove_client_full_address_remove_client_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.DateField(default=datetime.date.today, verbose_name='Месяц заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукция'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=100, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Компания-заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
