# Generated by Django 5.2.1 on 2025-06-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_order_unique_together'),
        ('users', '0004_remove_client_full_address_remove_client_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('client', 'product')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='month',
        ),
    ]
