# Generated by Django 5.2.6 on 2025-10-09 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Формат номера: +375XXXXXXXXX', regex='^\\+375\\d{9}$')]),
        ),
    ]
