# Generated by Django 5.2.1 on 2025-06-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_full_address_client_latitude_client_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
    ]
