# Generated by Django 5.2.1 on 2025-06-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_order_sale_date_order_completion_date_and_more'),
        ('users', '0004_remove_client_full_address_remove_client_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('client', 'product', 'month')},
        ),
    ]
