# Generated by Django 5.2.6 on 2025-10-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_pickuppoint_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('accepted', 'Принят')], default='new', max_length=20),
        ),
    ]
